;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        electric-newline-and-maybe-indent
        end-of-visual-line
        kill-visual-line
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-splice-sexp
        paredit-splice-sexp-killing-backward
        paredit-wrap-round
        reindent-then-newline-and-indent
        smex
        tuareg-electric-rp
        ))

(setq mc/cmds-to-run-once
      '(
        paredit-backward-kill-word
        paredit-close-round
        rectangle-number-lines
        undo-tree-visualize
        ))
