;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        end-of-visual-line
        ido-switch-buffer
        isearch-abort
        isearch-forward-regexp
        kill-visual-line
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-visual-line
        ido-switch-buffer
        ))
