(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(fringe-mode 0)
(global-hl-line-mode)
(global-visual-line-mode t)
(ido-mode t)
(global-font-lock-mode t)
(line-number-mode 1)
(column-number-mode 1)
(delete-selection-mode t)
(global-undo-tree-mode 1)
(tabbar-mode 1)
(auto-compression-mode t)
(turn-on-eval-sexp-fu-flash-mode)
;;(auto-insert-mode t)
(show-paren-mode t)
(global-auto-highlight-symbol-mode t)
(yas-global-mode 1)
(popwin-mode 1)
(recentf-mode 1)
(global-company-mode)
(projectile-global-mode)
(global-auto-revert-mode 1)
(global-subword-mode 1)
